services:
  # postgreSQL
  postgres:
    container_name: kickzone-database
    image: postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: kickzone
    ports:
      - 5432:5432
    restart: unless-stopped
    volumes:
      - /var/lib/postgresql/data
    networks:
      - kickzone-network
  # keycloak
  keycloak:
    container_name: kickzone-keycloak
    image: quay.io/keycloak/keycloak:latest
    ports:
      - 8080:8080
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    networks:
      - kickzone-network
    command:
      - "start-dev"

networks:
  kickzone-network:
    driver: bridge
volumes:
  postgres:
    driver: local